### ISSUE TITLE
Compiled module request

### ISSUE THREAD

**Issue by jonasfunk** [m1ga/com.miga.roundview#1]
Can't seem to build it, so would really appreciate if you would upload a compiled version of the module.

**Comment by jonasfunk** [comment]
Managed to get the module compiled by following this https://archive.appcelerator.com/question/149030/exec-returned-2-error-on-module-build.

**Comment by m1ga** [comment]
the compile module is under the release tab: https://github.com/m1ga/com.miga.roundview/releases
