### ISSUE TITLE
Module crashes app

### ISSUE THREAD

**Issue by jonasfunk** [m1ga/com.miga.roundview#2]
When setting an image url, I get an IOException.
I tried setting the url to both an external and internal url (located in assets/android/images).

**Comment by m1ga** [comment]
could you please paste the error message.  Are you using Android 6 with the new permissions?

**Comment by jonasfunk** [comment]
Thanks for getting back in this one. 
This is the error:
RoundView: (main) [0,19136]  EXCEPTION - IO
[WARN] :   TiDrawableReference: (main) [0,19136] Could not open stream to get bitmap
[WARN] :   TiDrawableReference: (main) [1,19137] Could not open stream to get bitmap

And yes, I use Android 6 with the new permissions.

**Comment by m1ga** [comment]
could you please try and put the image into /assets/images/ ?
I have the same error with android only assets. Will have a look at it soon!

**Comment by jonasfunk** [comment]
Hi, 
Tried putting assets in /assets/images/ but no luck - still crashes.

**Comment by m1ga** [comment]
That's strange. The code in the example if working fine for me with the image inside the asset/images/ folder. Could you please post your code so I can test your case

**Comment by jonasfunk** [comment]
```
var roundView = require('com.miga.roundview');        
var r = roundView.createRoundView({ 
   top: 340,
   height: 100,
   width: 100,
   cornerradius: 100,
   borderwidth: 10,
   bordercolor: "#f00",
   image: "/images/avatar_default.png",
   backgroundColor: "transparent"
});
```
<img width="174" alt="screen shot 2016-03-19 at 20 27 35" src="https://cloud.githubusercontent.com/assets/1299558/13900884/12b34fd6-ee11-11e5-9c9a-7e0485912d2b.png">

**Comment by m1ga** [comment]
working fine here. One change I did: ```bordercolor: "#ff0000"``` because of an error with the short form (will look into it). I've tried a png and a jpg, both showed up. My device: HTC A9 (6.0.1), SDK 5.1.2.GA

**Comment by jonasfunk** [comment]
Changing the bordercolor made it stop crashing. 
So far so good :) But no image is showing up - maybe just have to fiddle with it. 
My device is Nexus 5 (6.0.1), SDK 5.2.0.GA.
